// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BackendDioPredictionML.Model
{
    public class ModelInput
    {
        public float Price { get; set; }
        public float Bedrooms { get; set; }
        public float Bathrooms { get; set; }
        public float SqftLiving { get; set; }
        public float SqftLot { get; set; }
        public string Floors { get; set; }
        public float View { get; set; }
        public float Condition { get; set; }
        public float YearBuilt { get; set; }
        public float YearRenovated { get; set; }
        public float Grade { get; set; }
        public float SqftAbove { get; set; }
        public float SqftBasement { get; set; }


    }
}
