// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace BackendDioPrediction.HouseCommon.InputOutput
{
    public class HouseOutput
    {
        public float Score { get; set; }
    }
}
