// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using Newtonsoft.Json;

namespace BackendDioPrediction.HouseCommon.InputOutput
{
    public class HouseData
    {

        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Price"), LoadColumn(1)]
        public float Price { get; set; }


        [ColumnName("Bedrooms"), LoadColumn(2)]
        public float Bedrooms { get; set; }


        [ColumnName("Bathrooms"), LoadColumn(3)]
        public string Bathrooms { get; set; }


        [ColumnName("SqftLiving"), LoadColumn(4)]
        public float SqftLiving { get; set; }


        [ColumnName("SqftLot"), LoadColumn(5)]
        public float SqftLot { get; set; }


        [ColumnName("Floors"), LoadColumn(6)]
        public string Floors { get; set; }


        [ColumnName("View"), LoadColumn(7)]
        public float View { get; set; }


        [ColumnName("Condition"), LoadColumn(8)]
        public float Condition { get; set; }


        [ColumnName("YearBuilt"), LoadColumn(9)]
        public float YearBuilt { get; set; }


        [ColumnName("YearRenovated"), LoadColumn(10)]
        public float YearRenovated { get; set; }


        [ColumnName("Grade"), LoadColumn(11)]
        public float Grade { get; set; }


        [ColumnName("SqftAbove"), LoadColumn(12)]
        public float SqftAbove { get; set; }


        [ColumnName("SqftBasement"), LoadColumn(13)]
        public float SqftBasement { get; set; }

        public HouseData()
        {

        }
    }
}
