// This file was auto-generated by ML.NET Model Builder. 

using System;
using BackendDioPredictionML.Model;

namespace BackendDioPredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

        }
    }

}
